[package]
name = "bitcraps"
version = "0.1.0"
edition = "2021"
authors = ["BitCraps Team <dev@bitcraps.org>"]
description = "Decentralized craps casino over Bluetooth mesh with CRAP tokens"
license = "MIT OR Apache-2.0"

[dependencies]
# Core dependencies
thiserror = "2.0.16"
serde = { version = "1.0", features = ["derive"] }
bytes = "1.5"
byteorder = "1.5"
lz4_flex = "0.11"
uuid = { version = "1.6", features = ["v4", "serde"] }
tokio = { version = "1.47", features = ["full"] }
async-trait = "0.1"
futures = "0.3"

# Cryptography
snow = "0.10.0"
ed25519-dalek = { version = "2.0", features = ["rand_core"] }
x25519-dalek = "2.0"
rand = "0.8"
getrandom = "0.2"
sha2 = "0.10"
argon2 = "0.5.3"
chacha20poly1305 = "0.10.1"
hmac = "0.12"

# Bluetooth transport
btleplug = "0.11"

# Session management
chrono = { version = "0.4.41", features = ["serde"] }
bincode = "1.3"
hex = "0.4"

# CLI and UI
clap = { version = "4.5.45", features = ["derive"] }
ratatui = "0.29.0"
crossterm = "0.29.0"

# Persistence
rusqlite = { version = "0.32", features = ["bundled"] }
tokio-rusqlite = "0.6"

# Utilities
log = "0.4"
env_logger = "0.11"
toml = "0.8"
dirs = "5.0"
serde_json = "1.0"

[profile.release]
lto = true
codegen-units = 1
strip = true
opt-level = 3

[profile.dev]
opt-level = 0
debug = true