[package]
name = "bitchat"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "A decentralized, peer-to-peer messaging protocol implementation in Rust"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.99"
argon2 = "0.5.3"
base64 = "0.22.1"
bincode = "2.0.1"
bytes = "1.10.1"
chrono = "0.4.41"
clap = { version = "4.5.45", features = ["derive"] }
crossterm = "0.29.0"
ed25519-dalek = "2.2.0"
ethers-core = "2.0.14"
flate2 = "1.1.2"
hex = "0.4.3"
merkle-cbt = "0.3.2"
num-bigint = "0.4.6"
quinn = "0.11.8"
rand = "0.9.2"
ratatui = "0.29.0"
rusqlite = { version = "0.37.0", features = ["bundled"] }
secp256k1 = "0.31.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
sha2 = "0.10.9"
snow = "0.10.0"
thiserror = "2.0.16"
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
x25519-dalek = "2.0.1"
byteorder = "1.5.0"
lz4_flex = "0.11.3"
curve25519-dalek = "4.1.3"
getrandom = "0.2"

[dev-dependencies]
criterion = "0.7.0"
proptest = "1.7.0"

[profile.release]
lto = true
codegen-units = 1
strip = true
opt-level = 3

[profile.dev]
opt-level = 0
debug = true

[target."cfg(unix)".dependencies]
nix = { version = "0.30.1", features = ["net", "socket"] }

[target."cfg(windows)".dependencies]
windows = { version = "0.61.3", features = ["Win32_Networking_WinSock"] }
