[package]
name = "bitchat"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "A decentralized, peer-to-peer messaging protocol implementation in Rust"
license = "MIT OR Apache-2.0"

[dependencies]
thiserror = "2.0.16"

[profile.release]
lto = true
codegen-units = 1
strip = true
opt-level = 3

[profile.dev]
opt-level = 0
debug = true