apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bitcraps.fullname" . }}
  labels:
    {{- include "bitcraps.labels" . | nindent 4 }}
data:
  config.toml: |
    # BitCraps Production Configuration
    
    [general]
    log_level = "{{ .Values.config.logLevel }}"
    data_dir = "{{ .Values.env | first | pluck "value" | first }}"
    
    [network]
    bind_address = "0.0.0.0:8333"
    gateway_address = "0.0.0.0:8334"
    max_peers = {{ .Values.config.meshNetwork.maxPeers }}
    discovery_interval = {{ .Values.config.meshNetwork.discoveryInterval }}
    heartbeat_interval = {{ .Values.config.meshNetwork.heartbeatInterval }}
    enable_tls = {{ .Values.config.security.tlsEnabled }}
    
    [consensus]
    block_time = {{ .Values.config.consensus.blockTime }}
    validator_count = {{ .Values.config.consensus.validatorCount }}
    byzantine_threshold = 0.33
    
    [database]
    path = "{{ .Values.persistence.mountPath }}/bitcraps.db"
    wal_mode = {{ .Values.config.database.walMode }}
    checkpoint_interval = {{ .Values.config.database.checkpointInterval }}
    max_connections = {{ .Values.config.database.maxConnections }}
    
    [security]
    enforce_encryption = {{ .Values.config.security.enforceEncryption }}
    tls_cert = "/etc/bitcraps/tls/cert.pem"
    tls_key = "/etc/bitcraps/tls/key.pem"
    
    [monitoring]
    http_bind = "0.0.0.0:8080"
    metrics_bind = "0.0.0.0:9090"
    enable_metrics = true
    enable_health = true
    enable_ready = true
    
    [gaming]
    max_games = 1000
    max_players_per_game = 8
    game_timeout = 3600
    
    [incentives]
    reward_interval = 300
    base_reward = 100
    participation_bonus = 10
    
    {{- if .Values.postgresql.enabled }}
    [external_db]
    enabled = true
    type = "postgresql"
    host = "{{ include "bitcraps.fullname" . }}-postgresql"
    port = 5432
    database = "{{ .Values.postgresql.auth.database }}"
    username = "postgres"
    {{- end }}
    
    {{- if .Values.redis.enabled }}
    [cache]
    enabled = true
    type = "redis"
    host = "{{ include "bitcraps.fullname" . }}-redis-master"
    port = 6379
    {{- end }}