apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcraps-api-gateway
  namespace: bitcraps
  labels:
    app.kubernetes.io/name: bitcraps
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: kubernetes
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bitcraps
      app.kubernetes.io/component: api-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bitcraps
        app.kubernetes.io/component: api-gateway
        app.kubernetes.io/version: "0.1.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9090"
        config.linkerd.io/proxy-cpu-request: "100m"
        config.linkerd.io/proxy-memory-request: "128Mi"
    spec:
      serviceAccountName: bitcraps-api-gateway
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
      imagePullSecrets:
        - name: bitcraps-registry-secret
      containers:
      - name: api-gateway
        image: bitcraps/api-gateway:0.1.0
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        - name: health
          containerPort: 8081
          protocol: TCP
        env:
        - name: RUST_LOG
          value: "info,bitcraps::api=debug"
        - name: RUST_BACKTRACE
          value: "1"
        - name: API_PORT
          value: "8080"
        - name: METRICS_PORT
          value: "9090"
        - name: HEALTH_PORT
          value: "8081"
        - name: GAME_ENGINE_URL
          value: "http://bitcraps-game-engine:8000"
        - name: CONSENSUS_URL
          value: "http://bitcraps-consensus:8001"
        - name: MONITORING_URL
          value: "http://bitcraps-monitoring:9090"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: bitcraps-app-secrets
              key: jwt-secret
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: bitcraps-app-secrets
              key: encryption-key
        volumeMounts:
        - name: config
          mountPath: /etc/bitcraps
          readOnly: true
        - name: nginx-config
          mountPath: /etc/nginx
          readOnly: true
        - name: logs
          mountPath: /var/log/bitcraps
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /var/cache/nginx
        - name: run
          mountPath: /var/run
        livenessProbe:
          httpGet:
            path: /health
            port: health
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /ready
            port: health
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
          successThreshold: 1
        startupProbe:
          httpGet:
            path: /health
            port: health
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
          successThreshold: 1
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
            ephemeral-storage: 1Gi
          limits:
            cpu: 1
            memory: 2Gi
            ephemeral-storage: 5Gi
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 10"]
      volumes:
      - name: config
        configMap:
          name: bitcraps-app-config
          defaultMode: 0444
      - name: nginx-config
        configMap:
          name: bitcraps-nginx-config
          defaultMode: 0444
      - name: logs
        emptyDir:
          sizeLimit: 1Gi
      - name: tmp
        emptyDir:
          sizeLimit: 1Gi
      - name: cache
        emptyDir:
          sizeLimit: 1Gi
      - name: run
        emptyDir:
          sizeLimit: 100Mi
      terminationGracePeriodSeconds: 30
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: bitcraps
                  app.kubernetes.io/component: api-gateway
              topologyKey: kubernetes.io/hostname

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bitcraps-api-gateway
  namespace: bitcraps
  labels:
    app.kubernetes.io/name: bitcraps
    app.kubernetes.io/component: api-gateway
  annotations:
    description: "Service account for BitCraps API gateway"
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bitcraps-api-gateway
  namespace: bitcraps
  labels:
    app.kubernetes.io/name: bitcraps
    app.kubernetes.io/component: api-gateway
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bitcraps-api-gateway
  namespace: bitcraps
  labels:
    app.kubernetes.io/name: bitcraps
    app.kubernetes.io/component: api-gateway
subjects:
- kind: ServiceAccount
  name: bitcraps-api-gateway
  namespace: bitcraps
roleRef:
  kind: Role
  name: bitcraps-api-gateway
  apiGroup: rbac.authorization.k8s.io