apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcraps-game-engine
  namespace: bitcraps
  labels:
    app.kubernetes.io/name: bitcraps
    app.kubernetes.io/component: game-engine
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/managed-by: kubernetes
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: bitcraps
      app.kubernetes.io/component: game-engine
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bitcraps
        app.kubernetes.io/component: game-engine
        app.kubernetes.io/version: "0.1.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9090"
        config.linkerd.io/proxy-cpu-request: "100m"
        config.linkerd.io/proxy-memory-request: "128Mi"
    spec:
      serviceAccountName: bitcraps-game-engine
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
      imagePullSecrets:
        - name: bitcraps-registry-secret
      containers:
      - name: game-engine
        image: bitcraps/game-engine:0.1.0
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        - name: health
          containerPort: 8080
          protocol: TCP
        env:
        - name: RUST_LOG
          value: "info"
        - name: RUST_BACKTRACE
          value: "1"
        - name: APP_PORT
          value: "8000"
        - name: METRICS_PORT
          value: "9090"
        - name: HEALTH_PORT
          value: "8080"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: bitcraps-app-secrets
              key: db-host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: bitcraps-app-secrets
              key: db-port
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: bitcraps-app-secrets
              key: db-name
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: bitcraps-app-secrets
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bitcraps-app-secrets
              key: db-password
        - name: MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: bitcraps-app-secrets
              key: master-key
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: bitcraps-app-secrets
              key: encryption-key
        - name: SIGNING_KEY
          valueFrom:
            secretKeyRef:
              name: bitcraps-app-secrets
              key: signing-key
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: bitcraps-app-secrets
              key: jwt-secret
        volumeMounts:
        - name: config
          mountPath: /etc/bitcraps
          readOnly: true
        - name: data
          mountPath: /var/lib/bitcraps
        - name: logs
          mountPath: /var/log/bitcraps
        - name: tmp
          mountPath: /tmp
        livenessProbe:
          httpGet:
            path: /health
            port: health
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /health
            port: health
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
          successThreshold: 1
        startupProbe:
          httpGet:
            path: /health
            port: health
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
          successThreshold: 1
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
            ephemeral-storage: 1Gi
          limits:
            cpu: 2
            memory: 4Gi
            ephemeral-storage: 5Gi
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 15"]
      volumes:
      - name: config
        configMap:
          name: bitcraps-app-config
          defaultMode: 0444
      - name: data
        persistentVolumeClaim:
          claimName: bitcraps-game-data
      - name: logs
        emptyDir:
          sizeLimit: 1Gi
      - name: tmp
        emptyDir:
          sizeLimit: 1Gi
      terminationGracePeriodSeconds: 30
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: bitcraps
                  app.kubernetes.io/component: game-engine
              topologyKey: kubernetes.io/hostname
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bitcraps-game-engine
  namespace: bitcraps
  labels:
    app.kubernetes.io/name: bitcraps
    app.kubernetes.io/component: game-engine
  annotations:
    description: "Service account for BitCraps game engine"
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bitcraps-game-engine
  namespace: bitcraps
  labels:
    app.kubernetes.io/name: bitcraps
    app.kubernetes.io/component: game-engine
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bitcraps-game-engine
  namespace: bitcraps
  labels:
    app.kubernetes.io/name: bitcraps
    app.kubernetes.io/component: game-engine
subjects:
- kind: ServiceAccount
  name: bitcraps-game-engine
  namespace: bitcraps
roleRef:
  kind: Role
  name: bitcraps-game-engine
  apiGroup: rbac.authorization.k8s.io